import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import {
  Box,
  AppBar,
  Toolbar,
  IconButton,
  Typography,
  Button,
} from "@mui/material";
import { useRouter } from "next/router";
import Headers from "./Headers";
import { useEffect, useState } from "react";

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const [asd, setAsd] = useState(false);
  useEffect(() => {
    /** 로그인이 안되어있을시 회원가입화면으로 이동 (cookie 이용) */
    if (!asd) router.push("Join");
  }, []);

  return (
    <>
      <Head>
        <title>옥션 사이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <Component {...pageProps} />
      <footer>
        <Box sx={{ width: "150px" }}>
          <Typography>(주) 김앤장 네트워크</Typography>
        </Box>
      </footer>
    </>
  );
}
